-- Reviewable migration. Apply after card-confirmation and canonical installment columns.
-- Disabled by default: MERCADOPAGO_CARD_INSTALLMENTS_ENABLED must stay unset
-- until this RPC and real-provider/ledger validation have been approved.
begin;
create or replace function public.confirm_mercadopago_card_purchase(
  p_user_id uuid, p_connection_id uuid, p_candidate_id text,
  p_candidate_fingerprint text, p_intent_hash text, p_expected_observations jsonb,
  p_amount numeric, p_currency text, p_date date, p_category text,
  p_description text, p_is_want boolean, p_card_id uuid, p_installments integer, p_plan jsonb
) returns uuid
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_connection public.mercadopago_connections%rowtype;
  v_card public.cards%rowtype;
  v_review public.mercadopago_movement_reviews%rowtype;
  v_expense_id uuid;
  v_cycle_id uuid;
  v_raw public.mercadopago_raw_observations%rowtype;
  v_payload jsonb;
  v_expected jsonb;
  v_count integer;
  v_payment_count integer := 0;
  v_period date;
  v_closing date;
  v_due date;
  v_closing_day integer;
  v_due_day integer;
  v_provider_user_id text;
  v_method text;
  v_type text;
  v_role text;
  v_evidence jsonb;
  v_group_id uuid := gen_random_uuid();
  v_row jsonb;
  v_cycles jsonb;
  v_semantics jsonb;
  v_index integer := 0;
  v_first_cycle uuid;
  v_first_expense uuid;
  v_row_amount numeric;
  v_row_date date;
  v_expected_date date;

begin
  if p_user_id is null or p_connection_id is null or p_card_id is null
     or p_candidate_id is null or char_length(p_candidate_id) not between 1 and 256
     or p_candidate_fingerprint is null or p_intent_hash is null
     or p_candidate_fingerprint !~ '^[a-f0-9]{64}$' or p_intent_hash !~ '^[a-f0-9]{64}$'
     or p_expected_observations is null or jsonb_typeof(p_expected_observations) <> 'array'
     or jsonb_array_length(p_expected_observations) not between 1 and 2 or p_amount is null or p_amount <= 0
     or p_currency is null or p_amount::text in ('NaN','Infinity','-Infinity') or p_currency not in ('ARS','USD') or p_date is null or p_category is null
     or char_length(p_category) not between 1 and 50 or p_description is null
     or char_length(p_description) not between 1 and 100 or p_is_want is null or (p_installments is null or p_installments not between 2 and 72)
     or p_plan is null or jsonb_typeof(p_plan->'rows') is distinct from 'array'
     or jsonb_array_length(p_plan->'rows') <> p_installments
     or p_amount <> round(p_amount,2) then
    raise exception 'invalid card confirmation' using errcode='22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('gota-ledger:user:'||p_user_id::text,0));
  perform pg_advisory_xact_lock(hashtextextended('mp-confirm:connection:'||p_connection_id::text||':user:'||p_user_id::text,0));
  select * into v_connection from public.mercadopago_connections where id=p_connection_id and user_id=p_user_id and provider='mercadopago' and status='connected' for update;
  if not found then raise exception 'inactive connection' using errcode='P0002'; end if;
  select * into v_card from public.cards where id=p_card_id and user_id=p_user_id and archived=false for update;
  if not found then raise exception 'invalid or archived card' using errcode='P0002'; end if;
  if p_plan->'card' is distinct from jsonb_build_object('closing_day',v_card.closing_day,'due_day',v_card.due_day) then
    raise exception 'stale card configuration' using errcode='55000';
  end if;
  perform 1 from public.card_cycles where user_id=p_user_id and card_id=p_card_id order by period_month for update;
  select coalesce(jsonb_agg(jsonb_build_object('id',id,'period_month',period_month,'closing_date',closing_date,'due_date',due_date) order by period_month),'[]'::jsonb)
    into v_cycles from public.card_cycles where user_id=p_user_id and card_id=p_card_id;
  if p_plan->'existing_cycles' is distinct from v_cycles then raise exception 'stale cycle plan' using errcode='55000'; end if;
  v_semantics := jsonb_build_object('classification','human_confirmed_expense','provider_effect','credit_card_purchase','installments',p_installments,'rows',p_plan->'rows');
  -- Defense in depth for the plan generated by buildInstallmentRows. SQL does
  -- not plan cycles; the shared planner supplies them with a locked snapshot.
  for v_row in select value from jsonb_array_elements(p_plan->'rows') loop
    v_index := v_index+1;
    v_row_amount := (v_row->>'amount')::numeric;
    v_row_date := (v_row->>'date')::date;
    v_expected_date := (date_trunc('month',p_date)+(v_index-1)*interval '1 month')::date;
    v_expected_date := v_expected_date + least(extract(day from p_date)::integer, extract(day from (v_expected_date+interval '1 month - 1 day'))::integer)-1;
    if (v_row->>'installment_number')::integer is distinct from v_index or v_row_date is distinct from v_expected_date
       or v_row_amount is null or v_row_amount <= 0 or v_row_amount <> round(v_row_amount,2)
       or v_row_amount <> (floor(p_amount*100/p_installments) + case when v_index=p_installments then mod(p_amount*100,p_installments) else 0 end)/100
       or (v_row#>>'{cycle,period_month}') is null or (v_row#>>'{cycle,closing_date}') is null or (v_row#>>'{cycle,due_date}') is null then
      raise exception 'invalid canonical installment plan' using errcode='22023';
    end if;
  end loop;
  v_provider_user_id := v_connection.provider_user_id;
  select count(*) into v_count from jsonb_array_elements(p_expected_observations);
  if v_count <> (select count(distinct value->>'id') from jsonb_array_elements(p_expected_observations)) then
    raise exception 'duplicate evidence id' using errcode='22023';
  end if;
  for v_expected in select value from jsonb_array_elements(p_expected_observations) loop
    if not (v_expected ? 'id' and v_expected ? 'source' and v_expected ? 'native_key' and v_expected ? 'last_seen_at')
       or v_expected->>'source' not in ('payments_search','account_settlement_report') then
      raise exception 'invalid evidence item' using errcode='22023';
    end if;
    select * into v_raw from public.mercadopago_raw_observations where id=(v_expected->>'id')::uuid and user_id=p_user_id and connection_id=p_connection_id and source=v_expected->>'source' and native_key=v_expected->>'native_key' and last_seen_at=(v_expected->>'last_seen_at')::timestamptz for update;
    if not found then raise exception 'stale or foreign payment evidence' using errcode='P0002'; end if;
    if v_expected->>'source'='payments_search' then v_payment_count:=v_payment_count+1; v_payload:=v_raw.payload; end if;
  end loop;
  if v_payment_count <> 1 then raise exception 'exactly one payment source required' using errcode='22023'; end if;
  v_method := lower(coalesce(v_payload->>'PAYMENT_METHOD_TYPE',v_payload->>'payment_type_id',v_payload#>>'{payment_method,type}',''));
  v_type := coalesce(v_payload->>'operation_type','');
  v_role := case when coalesce(v_payload->>'payer_id',v_payload#>>'{payer,id}') = v_provider_user_id then 'payer' else 'other' end;
  if v_payload->>'status' <> 'approved' or v_type not in ('regular_payment','recurring_payment') or v_role <> 'payer'
     or v_method <> 'credit_card' or coalesce((v_payload#>>'{transaction_details,total_paid_amount}')::numeric,(v_payload->>'transaction_amount')::numeric,(v_payload->>'amount')::numeric,0) <> p_amount
     or coalesce(v_payload->>'currency_id',v_payload->>'currency') <> p_currency
     or (v_payload->>'transaction_amount_refunded') is not null and (v_payload->>'transaction_amount_refunded')::numeric <> 0
     or coalesce(v_payload->>'status_detail','') in ('charged_back','in_mediation','refunded')
     or (v_payload->>'installments') is null or (v_payload->>'installments')::integer <> p_installments
     or coalesce(v_payload->>'date_created',v_payload->>'date') is null
     or ((coalesce(v_payload->>'date_created',v_payload->>'date'))::timestamptz at time zone 'America/Argentina/Buenos_Aires')::date <> p_date then
    raise exception 'provider candidate is not an eligible credit purchase' using errcode='22023';
  end if;
  select jsonb_build_object('observations',coalesce(jsonb_agg(jsonb_build_object('id',e.item->>'id','source',e.item->>'source','native_key',e.item->>'native_key') order by e.item->>'source',e.item->>'native_key',e.item->>'id'),'[]'::jsonb)) into v_evidence from jsonb_array_elements(p_expected_observations) as e(item);
  select * into v_review from public.mercadopago_movement_reviews where user_id=p_user_id and connection_id=p_connection_id and candidate_id=p_candidate_id for update;
  if found then
    if v_review.candidate_fingerprint is distinct from p_candidate_fingerprint
       or v_review.intent_hash is distinct from p_intent_hash then raise exception 'card confirmation replay conflict' using errcode='23505'; end if;
    if v_review.status is distinct from 'confirmed'
       or v_review.evidence is distinct from v_evidence
       or v_review.card_id is distinct from p_card_id
       or v_review.card_cycle_id is null
       or v_review.canonical_amount is distinct from p_amount
       or v_review.canonical_currency is distinct from p_currency
       or v_review.canonical_date is distinct from p_date
       or v_review.canonical_description is distinct from p_description
       or v_review.canonical_category is distinct from p_category
       or v_review.is_want is distinct from p_is_want
       or v_review.canonical_semantics is distinct from v_semantics
       or v_review.evidence_kind is distinct from 'credit_card_purchase' then
      raise exception 'card confirmation replay invariant conflict' using errcode='23505';
    end if;
    select installment_group_id into v_group_id from public.expenses where id=v_review.expense_id and user_id=p_user_id;
    if v_group_id is null or (select count(*) from public.expenses where installment_group_id=v_group_id) <> p_installments then
      raise exception 'replay installment group missing' using errcode='P0002';
    end if;
    for v_row in select value from jsonb_array_elements(p_plan->'rows') loop
      if not exists(select 1 from public.expenses e join public.card_cycles c on c.id=e.card_cycle_id
        where e.user_id=p_user_id and e.installment_group_id=v_group_id and e.installment_number=(v_row->>'installment_number')::integer
          and e.installment_total=p_installments and e.amount=(v_row->>'amount')::numeric and e.date::date=(v_row->>'date')::date
          and e.currency=p_currency and e.category=p_category and e.description=p_description and e.is_want=p_is_want
          and e.payment_method='CREDIT' and e.card_id=p_card_id and e.account_id is null
          and c.user_id=p_user_id and c.card_id=p_card_id and c.period_month=(v_row#>>'{cycle,period_month}')::date
          and c.closing_date=(v_row#>>'{cycle,closing_date}')::date and c.due_date=(v_row#>>'{cycle,due_date}')::date) then
        raise exception 'replay installment changed' using errcode='P0002';
      end if;
    end loop;
    return v_review.expense_id;
  end if;
  if exists(select 1 from public.mercadopago_movement_reviews where user_id=p_user_id and connection_id=p_connection_id and candidate_fingerprint=p_candidate_fingerprint)
     or exists(select 1 from public.mercadopago_movement_dismissals where user_id=p_user_id and connection_id=p_connection_id and (candidate_id=p_candidate_id or candidate_fingerprint=p_candidate_fingerprint)) then
    raise exception 'candidate already decided' using errcode='55000';
  end if;
  if exists(select 1 from (select evidence from public.mercadopago_movement_reviews where user_id=p_user_id and connection_id=p_connection_id
      union all select evidence from public.mercadopago_movement_dismissals where user_id=p_user_id and connection_id=p_connection_id) prior,
      jsonb_array_elements(prior.evidence->'observations') old,jsonb_array_elements(p_expected_observations) incoming
      where old->>'native_key'=incoming->>'native_key') then
    raise exception 'provider evidence already decided' using errcode='23505';
  end if;
  for v_row in select value from jsonb_array_elements(p_plan->'rows') loop
    v_period := (v_row#>>'{cycle,period_month}')::date;
    v_closing := (v_row#>>'{cycle,closing_date}')::date;
    v_due := (v_row#>>'{cycle,due_date}')::date;
    insert into public.card_cycles(user_id,card_id,period_month,closing_date,due_date,status)
      values(p_user_id,p_card_id,v_period,v_closing,v_due,'open') on conflict(card_id,period_month) do nothing;
    select id into strict v_cycle_id from public.card_cycles where user_id=p_user_id and card_id=p_card_id
      and period_month=v_period and closing_date=v_closing and due_date=v_due for update;
    insert into public.expenses(user_id,amount,currency,category,description,is_want,payment_method,card_id,card_cycle_id,account_id,date,installment_group_id,installment_number,installment_total)
      values(p_user_id,(v_row->>'amount')::numeric,p_currency,p_category,p_description,p_is_want,'CREDIT',p_card_id,v_cycle_id,null,(v_row->>'date')::date::timestamptz,v_group_id,(v_row->>'installment_number')::integer,p_installments) returning id into v_expense_id;
    if v_first_expense is null then v_first_expense:=v_expense_id; v_first_cycle:=v_cycle_id; end if;
  end loop;
  v_expense_id:=v_first_expense; v_cycle_id:=v_first_cycle;
  insert into public.mercadopago_movement_reviews(user_id,connection_id,candidate_id,candidate_fingerprint,intent_hash,status,expense_id,account_id,card_id,card_cycle_id,canonical_amount,canonical_currency,canonical_date,canonical_category,canonical_description,is_want,canonical_semantics,evidence,evidence_kind,decision_source,decision_rule_version,decision_reason)
  values(p_user_id,p_connection_id,p_candidate_id,p_candidate_fingerprint,p_intent_hash,'confirmed',v_expense_id,null,p_card_id,v_cycle_id,p_amount,p_currency,p_date,p_category,p_description,p_is_want,v_semantics,v_evidence,'credit_card_purchase','human',3,'approved_credit_purchase_installments');
  return v_expense_id;
end;
$$;
revoke all on function public.confirm_mercadopago_card_purchase(uuid,uuid,text,text,text,jsonb,numeric,text,date,text,text,boolean,uuid,integer,jsonb) from public,anon,authenticated;
grant execute on function public.confirm_mercadopago_card_purchase(uuid,uuid,text,text,text,jsonb,numeric,text,date,text,text,boolean,uuid,integer,jsonb) to service_role;

commit;
